<?php
/*************************
  Copyright (c) 2004-2014 TinyWebGallery 
  written by Michael Dempfle
  
  This program is free software; you can redistribute it and/or modify  
  it under the terms of the TinyWebGallery license (based on the GNU
  General Public License as published by the Free Software Foundation;  
  either version 2 of the License, or (at your option) any later version. 
  See license.txt for details.

  Generated by TWG admin at 25.05.14 01:05:37
**********************************************/

/*
This is the basic administration file created by TWG admin.

If you want to configure TWG in more detail you can copy aditional settings from
the config.php to this file.

PLEASE NOTE: If you copy additional settings to this file you should NOT use the
frontend of TWG admin anymore because this file is generated if you save it there!

I have stored the most important settings for TWG here - config.php has around 400
different settings where most of the settings shown here, can be configured in more
detail + many more options are available! e.g. email notification ...
Please check the config.php if you want to adapt one of the settings to your needs!
*/
/** ensure this file is being included by a parent file */
defined( '_VALID_TWG' ) or die( 'Direct Access to this location is not allowed.' );


/* ----------------------------------------------------------------------------
    PLEASE NOTE: This file does only contain the delta to the main config.php!
   ---------------------------------------------------------------------------- */

$browser_title_prefix= 'CIN Gallery';     // (String) This is the title which is shown in the browser title - you may change this to the name of your gallery
$default_gallery_title= '';               // (String) This is the default title shown on the main page if no real $lang_titel is specified in the language file. If you want to have different titles for a language please adapt the language files!
$skin= 'integrated';                      // (String) As default no skin is used - in the download  are 'black','green','transparent','winter' and 'newyork'  . All other style settings are still valid (check how-to 9). Some of the skin have a background! Check the Skins how-to to create your own skin or look in the forum of TWG - there is a skins section. if you change the skin you have to delete the *.slide.jpg images in the cache folder!

$autorotate_images= 'invert';             // (String) ('','normal','invert') TWG can autodetect the orientation of images if your camera set this. The problem is that TWG does not know how you hold your camera. if you like no autorotation use '', If you want normal rotation use 'normal', If the images are all rotated 180 Degrees use 'invert'. I have set 'invert' as default because I always hold my camera like this + 2 other camera is tested did the same ;).

$show_comments= false;                    // (true/false) enable comments and shows them below the pictures !!  - if you set this to false make sure that the $topx_default does not point to comments
$show_login= false;                       // (true/false) enables/disables the login button in the right upper corner
$show_optionen= false;                    // (true/false) enables/disables the options button in the right upper corner on the details page
$show_new_window= false;                  // (true/false) enables/disables the 'new window' button in the right upper corner and in the options pane.
$show_image_rating= false;                // (true/false) Enables the rating of images
$show_search= false;                      // (true/false) shows the search
$show_public_admin_link= false;           // (true/false) enables disables the link to the admin area !
$show_image_rating= false;                // (true/false) Enables the rating of images
$show_tags= false;                        // (true/false) Show the top tags - the search for tags and the posiblility to enter tags at the detail page when logged in.


/*
This is a helper variable for reloading your extra settings. If you add a new parameter manually
you have to add it to this variable too - otherwise it will be removed if the config
is changed by TWG admin! $ and " have to be escaped!! New lines are saved as -NL-
*/
$additional="";
/* extra parameters set in the additional page in the TWG admin */


// PLEASE ONLY ADD PARAMETERS HERE IF YOU DON'T USE TWG ADMINISTRATION. OTHERWISE THE PARAMETERS 
// GET REMOVED THE NEXT TIME YOU SAVE THE SETTINGS THERE
// PLEASE ADD YOUR SETTINGS IN THE FREE TEXT FIELD OF THE CONFIG.

?>